# Generated by Django 4.1.3 on 2023-01-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_employeeid_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('financeofficer_id', models.AutoField(primary_key=True, serialize=False)),
                ('financeofficer_name', models.CharField(max_length=40, null=True)),
                ('financeofficer_contact', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=40, null=True)),
                ('manager_contact', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('manager_remark', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField()),
                ('marked_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manager')),
                ('submitted_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('purchaser_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchaser_name', models.CharField(max_length=40, null=True)),
                ('purchaser_contact', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=40, null=True)),
                ('vendor_contact', models.CharField(max_length=15, null=True)),
                ('vendor_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrItem',
            fields=[
                ('pr_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_item_name', models.CharField(max_length=40, null=True)),
                ('pr_item_qty', models.PositiveIntegerField(default=None, null=True)),
                ('pr_item_price', models.FloatField(default=None, null=True)),
                ('pr_item_description', models.CharField(default=None, max_length=100, null=True)),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pr')),
            ],
        ),
    ]
