# Generated by Django 4.1.3 on 2023-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vendor_vendor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='financeofficer',
            name='financeofficer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='purchaser_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=models.CharField(blank=True, default=True, max_length=15, null=True),
        ),
    ]
