# Generated by Django 4.1.3 on 2023-01-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('total_price', models.FloatField(default=None, null=True)),
                ('date_of_expiry', models.DateField()),
                ('q_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.purchaser')),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pr')),
            ],
        ),
        migrations.AddField(
            model_name='pritem',
            name='pr_item_unit_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pritem',
            name='pr_item_description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('q_item_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('q_item_name', models.CharField(max_length=20, null=True)),
                ('q_item_unit_price', models.FloatField(default=None, null=True)),
                ('q_item_qty', models.PositiveIntegerField(default=None, null=True)),
                ('q_item_price', models.FloatField(default=None, null=True)),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vendor'),
        ),
    ]
