# Generated by Django 4.1.3 on 2023-01-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quotation_pritem_pr_item_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritem',
            name='pr_item_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='vendor_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.vendor'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='q_item_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('q_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('financeOfficerId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.financeofficer')),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pr')),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('po_item_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('po_item_name', models.CharField(max_length=20, null=True)),
                ('po_unit_price', models.FloatField(default=None, null=True)),
                ('po_item_qty', models.PositiveIntegerField(default=None, null=True)),
                ('po_item_price', models.FloatField(blank=True, default=None, null=True)),
                ('po_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorder')),
            ],
        ),
    ]
