# Generated by Django 4.1.3 on 2023-01-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_pritem_pr_item_price_alter_quotation_vendor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
