# Generated by Django 4.1.3 on 2023-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='manager_remark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='q_payment_terms',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
