# Generated by Django 4.1.3 on 2023-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_pritem_pr_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='purchaser_remark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
