# Generated by Django 4.1.3 on 2023-01-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_poitem_po_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='q_payment_terms',
            new_name='po_terms',
        ),
    ]
