# Generated by Django 4.1.3 on 2023-01-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_q_payment_terms_purchaseorder_po_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
