# Generated by Django 4.1.3 on 2023-01-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_manager_manager_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
